
#ifndef HEADER_CL_ERR_H
# define HEADER_CL_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_CL_strings(void);
static void ERR_unload_CL_strings(void);
static void ERR_CL_error(int function, int reason, char *file, int line);
# define CLerr(f,r) ERR_CL_error((f),(r),__FILE__,__LINE__)

/* Error codes for the CL functions. */

/* Function codes. */
# define CL_F_CLUSTER_LABS_CTRL                           100
# define CL_F_CLUSTER_LABS_DSA_SIGN                       101
# define CL_F_CLUSTER_LABS_DSA_VERIFY                     102
# define CL_F_CLUSTER_LABS_FINISH                         103
# define CL_F_CLUSTER_LABS_INIT                           104
# define CL_F_CLUSTER_LABS_MOD_EXP                        105
# define CL_F_CLUSTER_LABS_MOD_EXP_CRT                    106
# define CL_F_CLUSTER_LABS_RAND_BYTES                     107
# define CL_F_CLUSTER_LABS_RSA_MOD_EXP                    108
# define CL_F_CLUSTER_LABS_RSA_PRIV_DEC                   109
# define CL_F_CLUSTER_LABS_RSA_PRIV_ENC                   110
# define CL_F_CLUSTER_LABS_RSA_PUB_DEC                    111
# define CL_F_CLUSTER_LABS_RSA_PUB_ENC                    112

/* Reason codes. */
# define CL_R_ALREADY_LOADED                              100
# define CL_R_COMMAND_NOT_IMPLEMENTED                     101
# define CL_R_DSO_FAILURE                                 102
# define CL_R_FUNCTION_NOT_BINDED                         103
# define CL_R_INIT_FAILED                                 104
# define CL_R_NOT_LOADED                                  105

#ifdef  __cplusplus
}
#endif
#endif
