
#ifndef HEADER_ATALLA_ERR_H
# define HEADER_ATALLA_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_ATALLA_strings(void);
static void ERR_unload_ATALLA_strings(void);
static void ERR_ATALLA_error(int function, int reason, char *file, int line);
# define ATALLAerr(f,r) ERR_ATALLA_error((f),(r),__FILE__,__LINE__)

/* Error codes for the ATALLA functions. */

/* Function codes. */
# define ATALLA_F_ATALLA_CTRL                             100
# define ATALLA_F_ATALLA_FINISH                           101
# define ATALLA_F_ATALLA_INIT                             102
# define ATALLA_F_ATALLA_MOD_EXP                          103
# define ATALLA_F_ATALLA_RSA_MOD_EXP                      104

/* Reason codes. */
# define ATALLA_R_ALREADY_LOADED                          100
# define ATALLA_R_BN_CTX_FULL                             101
# define ATALLA_R_BN_EXPAND_FAIL                          102
# define ATALLA_R_CTRL_COMMAND_NOT_IMPLEMENTED            103
# define ATALLA_R_MISSING_KEY_COMPONENTS                  104
# define ATALLA_R_NOT_LOADED                              105
# define ATALLA_R_REQUEST_FAILED                          106
# define ATALLA_R_UNIT_FAILURE                            107

#ifdef  __cplusplus
}
#endif
#endif
