

#ifndef HEADER_GMP_ERR_H
# define HEADER_GMP_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_GMP_strings(void);
static void ERR_unload_GMP_strings(void);
static void ERR_GMP_error(int function, int reason, char *file, int line);
# define GMPerr(f,r) ERR_GMP_error((f),(r),__FILE__,__LINE__)

/* Error codes for the GMP functions. */

/* Function codes. */
# define GMP_F_E_GMP_CTRL                                 100
# define GMP_F_E_GMP_RSA_MOD_EXP                          101

/* Reason codes. */
# define GMP_R_CTRL_COMMAND_NOT_IMPLEMENTED               100
# define GMP_R_KEY_CONTEXT_ERROR                          101
# define GMP_R_MISSING_KEY_COMPONENTS                     102

#ifdef  __cplusplus
}
#endif
#endif
