
#ifndef HEADER_NURON_ERR_H
# define HEADER_NURON_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_NURON_strings(void);
static void ERR_unload_NURON_strings(void);
static void ERR_NURON_error(int function, int reason, char *file, int line);
# define NURONerr(f,r) ERR_NURON_error((f),(r),__FILE__,__LINE__)

/* Error codes for the NURON functions. */

/* Function codes. */
# define NURON_F_NURON_CTRL                               100
# define NURON_F_NURON_FINISH                             101
# define NURON_F_NURON_INIT                               102
# define NURON_F_NURON_MOD_EXP                            103

/* Reason codes. */
# define NURON_R_ALREADY_LOADED                           100
# define NURON_R_CTRL_COMMAND_NOT_IMPLEMENTED             101
# define NURON_R_DSO_FAILURE                              102
# define NURON_R_DSO_FUNCTION_NOT_FOUND                   103
# define NURON_R_DSO_NOT_FOUND                            104
# define NURON_R_NOT_LOADED                               105

#ifdef  __cplusplus
}
#endif
#endif
