
#ifndef HEADER_SUREWARE_ERR_H
# define HEADER_SUREWARE_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_SUREWARE_strings(void);
static void ERR_unload_SUREWARE_strings(void);
static void ERR_SUREWARE_error(int function, int reason, char *file,
                               int line);
# define SUREWAREerr(f,r) ERR_SUREWARE_error((f),(r),__FILE__,__LINE__)

/* Error codes for the SUREWARE functions. */

/* Function codes. */
# define SUREWARE_F_SUREWAREHK_CTRL                       100
# define SUREWARE_F_SUREWAREHK_DH_EX_FREE                 112
# define SUREWARE_F_SUREWAREHK_DSA_DO_SIGN                101
# define SUREWARE_F_SUREWAREHK_EX_FREE                    102
# define SUREWARE_F_SUREWAREHK_FINISH                     103
# define SUREWARE_F_SUREWAREHK_INIT                       104
# define SUREWARE_F_SUREWAREHK_LOAD_PRIVKEY               105
# define SUREWARE_F_SUREWAREHK_LOAD_PUBKEY                113
# define SUREWARE_F_SUREWAREHK_MODEXP                     107
# define SUREWARE_F_SUREWAREHK_RAND_BYTES                 108
# define SUREWARE_F_SUREWAREHK_RAND_SEED                  109
# define SUREWARE_F_SUREWAREHK_RSA_PRIV_DEC               110
# define SUREWARE_F_SUREWAREHK_RSA_SIGN                   111
# define SUREWARE_F_SUREWARE_LOAD_PUBLIC                  106

/* Reason codes. */
# define SUREWARE_R_BIO_WAS_FREED                         100
# define SUREWARE_R_MISSING_KEY_COMPONENTS                105
# define SUREWARE_R_PADDING_CHECK_FAILED                  106
# define SUREWARE_R_REQUEST_FAILED                        101
# define SUREWARE_R_REQUEST_FALLBACK                      102
# define SUREWARE_R_SIZE_TOO_LARGE_OR_TOO_SMALL           103
# define SUREWARE_R_UNIT_FAILURE                          104
# define SUREWARE_R_UNKNOWN_PADDING_TYPE                  107

#ifdef  __cplusplus
}
#endif
#endif
